name: Secret Scan CI

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest \
          | grep "browser_download_url.*linux_x64.tar.gz" \
          | cut -d '"' -f 4 \
          | wget -qi -
          tar -xzf gitleaks_*.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks Scan
        run: |
          gitleaks detect --source . --verbose --no-git -r report.json || echo "SECRETS_FOUND=true" >> $GITHUB_ENV

      - name: Stop pipeline if secrets found
        if: env.SECRETS_FOUND == 'true'
        run: |
          echo "Hardcoded credentials detected! Stopping pipeline..."
          exit 1

      - name: Send Email Notification
        if: env.SECRETS_FOUND == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Hardcoded credentials found in commit"
          to: developer@example.com
          from: CI/CD Pipeline
          body: |
            Your recent commit contains hardcoded credentials. 
            Please remove them and push again.
